implemented directories
cryptic-game/cryptic-device pull request #66
Opened 2019-10-03 21:44 UTC by TheCataliasTNT2k

## Description
- implemented directories ("is_directory" is used to indicated if a file is a directory)
- added "parent_dir_uuid" to link to the parrent directory of the file 
- added boolean changeable to File, to prevent "/" file from being moved or deleted
- device creation also creates "/"
- directories can no longer moved inside itself or its child directories
- not changeable files can no longer be changed

## Related Issue
#46 

## Motivation and Context
Now there are directories not only files

## How Has This Been Tested?
not yet tested, unit tests will follow

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2019-10-14 23:52 UTC, Defelo requested changes
In the `["file", "create"]` endpoint you should check if the parent directory is actually a directory (done). Currently it is possible to create files in other files. Also it should not be possible to create files outside of the root directory, so `parent_dir_uuid` may not be `None` (done)

2019-10-15 10:42 UTC, Defelo commented
In the `["device", "delete"]` endpoint you should also delete all files on the device.

2019-10-15 11:00 UTC, Defelo commented on app/resources/device.py
> +
You already deleted the files above

2019-10-15 11:04 UTC, Defelo commented on app/resources/file.py
> +    if not parent_dir:
You also need to check if the parent is actually a directory:
```suggestion
    if not (parent_dir and parent_dir.is_directory):
```

2019-10-16 12:10 UTC, Defelo commented on app/resources/file.py
> +    parent_dir: File = wrapper.session.query(File).filter_by(device=device.uuid, parent_dir_uuid=parent_dir_uuid,
wrong query
```suggestion
    parent_dir: File = wrapper.session.query(File).filter_by(device=device.uuid, uuid=parent_dir_uuid,
```

2019-10-17 18:31 UTC, Defelo approved these changes

2019-10-17 20:55 UTC, Defelo requested changes

2019-10-17 20:55 UTC, Defelo commented on app/schemes.py
> +parent_dir_does_not_exist: dict = make_error("parent directory for new file does not exist", origin="user")
duplicate error message for `parent_directory_not_found` -> delete this

2019-10-17 20:55 UTC, Defelo commented on app/resources/file.py
> +        return parent_dir_does_not_exist
use `parent_directory_not_found` instead

2019-10-17 21:15 UTC, Defelo approved these changes

2019-10-25 14:48 UTC, Defelo requested changes
Device names may only consist of alphanumeric characters plus `-` and `_`. Similarly file names my only consist of alphanumeric characters plus `-`, `_` and `.`. (done)

2019-10-25 22:24 UTC, Defelo approved these changes

2019-11-01 14:05 UTC, MaxiHuHe04 requested changes
https://github.com/cryptic-game/frontend/pull/82#discussion_r341569568
Please add a notification for when files get created, deleted and changed. It should contain the affected file(s).  The structure could be for example:
```json
{
    "notify-id": "file-update",
    "origin": "<create/delete/update [string]>",
    "device_uuid": "<UUID of the affected device [string, UUID]>",
    "data": {
        "created": ["<UUID of the created file [string, UUID]>"],
        "deleted": ["<UUID of the deleted file {string, UUID]>"],
        "changed": ["<UUID of the changed file [string, UUID]>"]
    }
}
```

2019-11-02 13:22 UTC, MaxiHuHe04 approved these changes

2019-11-21 07:49 UTC, Defelo requested changes
Remove the `/` directory. Instead for all files in the root directory `parent_dir_uuid` should be `None` (done)

2019-12-01 00:03 UTC, Defelo approved these changes

2020-02-17 20:13 UTC, merged