Device hardwareconfig
cryptic-game/cryptic-device pull request #83
Opened 2020-01-06 00:03 UTC by Defelo

## Description
Updated game config and fixed hardware compatibility and performance calculation

## How Has This Been Tested?
unit tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-01-19 16:33 UTC, DevMimas approved these changes

2020-04-01 21:04 UTC, TheCataliasTNT2k requested changes

2020-04-01 21:04 UTC, TheCataliasTNT2k commented on app/resources/game_content.py
> +    if case != hardware["mainboard"][mainboard]["case"]:
What if multiple mainboards and multiple cases are compatible?

2020-04-01 21:04 UTC, TheCataliasTNT2k commented on app/resources/game_content.py
> +        if interface not in expansion_slots or expansion_slots[interface] <= 0:
<0? when should this be true?

2020-04-01 21:04 UTC, TheCataliasTNT2k commented on app/resources/game_content.py
> +        if remaining_disk_slots <= 0 or interface not in hardware["mainboard"][mainboard]["diskStorage"]["interface"]:
same as above

2020-04-01 21:04 UTC, TheCataliasTNT2k commented on app/resources/game_content.py
> +            calc_gpu_performance,
missing function parameters?

2020-04-01 21:04 UTC, TheCataliasTNT2k commented on app/resources/game_content.py
> +    for element_type in ("mainboard", "powerPack", "case"):
what happens with
`elements = {}`?
error, because of KeyError?

2020-04-01 21:18 UTC, Defelo commented on app/resources/game_content.py
> +    if case != hardware["mainboard"][mainboard]["case"]:
there is only one case and one mainboard, so we just need to check if they are compatible

2020-04-01 21:23 UTC, Defelo commented on app/resources/game_content.py
> +        if interface not in expansion_slots or expansion_slots[interface] <= 0:
every gpu uses up one expansion_slot. so this checks if all expansion_slots are used up or if there are any expansion_slots left

2020-04-01 21:23 UTC, Defelo commented on app/resources/game_content.py
> +        if remaining_disk_slots <= 0 or interface not in hardware["mainboard"][mainboard]["diskStorage"]["interface"]:
same as above

2020-04-01 21:31 UTC, Defelo commented on app/resources/game_content.py
> +            calc_gpu_performance,
no, just read about the [map function](https://docs.python.org/3/library/functions.html#map)

2020-04-01 21:33 UTC, Defelo commented on app/resources/game_content.py
> +    for element_type in ("mainboard", "powerPack", "case"):
yes, this would result in a `KeyError`, but the `create_hardware` function is always called with the correct parameters

2020-04-01 22:28 UTC, TheCataliasTNT2k approved these changes

2020-04-01 22:30 UTC, merged